services:
  avigor-website:
    image: ghcr.io/larswillrich/avigor:latest
    restart: unless-stopped
    environment:
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_SECURE=${SMTP_SECURE:-false}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    labels:
      - traefik.enable=true
      - traefik.http.routers.avigorwebsite.rule=Host(`avigor.de`) || Host(`www.avigor.de`)
      - traefik.http.routers.avigorwebsite.tls=true
      - traefik.http.routers.avigorwebsite.entrypoints=web,websecure
      - traefik.http.routers.avigorwebsite.tls.certresolver=mytlschallenge
    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    external: true
