services:
  avigor-website:
    image: ghcr.io/larswillrich/avigor:latest
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.avigorwebsite.rule=Host(`avigor.de`)
      - traefik.http.routers.avigorwebsite.tls=true
      - traefik.http.routers.avigorwebsite.entrypoints=web,websecure
      - traefik.http.routers.avigorwebsite.tls.certresolver=mytlschallenge
    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    external: true
